name: Build and public docker image

on:
  push:
    branches: "master"

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAMESPACE: testwydimage
  IMAGE_NAME: ebpf-injector-2

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # 1. 安装编译依赖
      # 关键：加入了 gcc-multilib，专门解决 stubs-32.h 报错
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          libelf1 libelf-dev zlib1g-dev libclang-dev \
          make git clang llvm pkg-config build-essential \
          gcc-multilib

      # 2. 在宿主机直接编译
      # 这里环境齐全，不需要下载 BTF，直接编译成功
      - name: build package
        run: |
          cd src
          make

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME_ALI }}
          password: ${{ secrets.PASSWORD_ALI }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: type=ref,event=branch,prefix=

      - name: Build image and push to Aliyun
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
